²
CREATE DATABASE `languages`;
CREATE DATABASE `webDevelopment` CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS `frameworks` CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS `languages` CHARACTER SET 'utf8';
DROP DATABASE `languages`;
DROP DATABASE IF EXISTS `frameworks`;
DROP DATABASE IF EXISTS `languages`;
